### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nordpixilus** [andrey-helldar/laravel-app#1]
Caching was disabled received an error. Perhaps it is necessary to warn other users. Thanks.

**Comment by andrey-helldar** [comment]
This package contains the command from Laravel 5.8.
It does not use caching when changing the namespace of the project and changing the environment settings does not affect its operation.

![2019-10-24_11-34-58](https://user-images.githubusercontent.com/10347617/67468098-99d2f000-f652-11e9-9a23-09820dff8556.png)

![2019-10-24_11-36-03](https://user-images.githubusercontent.com/10347617/67468100-9a6b8680-f652-11e9-85f4-4336e1bbaa0c.png)

![2019-10-24_11-35-23](https://user-images.githubusercontent.com/10347617/67468101-9a6b8680-f652-11e9-9325-fa526b42185c.png)

**Comment by andrey-helldar** [comment]
At the end of the namespace change, command `optimize:clear` is called, which performs the following actions (see [Illuminate/Foundation/Console/OptimizeClearCommand](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Console/OptimizeClearCommand.php#L28))

- view:clear
- cache:clear
- route:clear
- config:clear
- clear-compiled
