### ISSUE TITLE
Include /tests folder when renaming app?

### ISSUE THREAD

**Issue by Arxcis** [andrey-helldar/laravel-app#2]
I usually have alot of `use App\FooClass` in my tests

**Example:**
```php
<?php

namespace tests\Api;

use App\Http\Resources\CompanyResource;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Http\Response;

class CompanyTest extends \Tests\BaseTest
{
    use DatabaseTransactions;

    public function testGetIndex()
    {
// ....
```
I had to manually rename `App` -> `Api` in the tests. Not a big problem. Just mentioning it as a potential improvement of this tool. 

Thank you for making this repo available to the public :+1:

**Comment by andrey-helldar** [comment]
Thanks for the information!

This package will not be developed, since it is officially disabled from the framework.

The package was created according to the latest stable version of the script.

**Comment by Arxcis** [comment]
Ok. No worries. I understand :)
