### ISSUE TITLE
Problems to use the Factories and Seeding after change the namespace name

### ISSUE THREAD

**Issue by douglasmiguel** [andrey-helldar/laravel-app#4]
Hi, I was debugging why the factories and seeding were not working for me after use your lib to update the namespace and I realized that the Factory lib uses a hard-coded reference to `App`:

`Illuminate\Database\Eloquent\Factories\Factory`, line 680 (`resolveFactoryName`).

I had to revert the changes.

**Comment by andrey-helldar** [comment]
The code for this package is taken from the original Laravel 6 repository. It is compatible with Laravel 7 and partially compatible with the eighth version.

I published a patch to remove support for Laravel 8 and transferred the package to abandoned status.
