### ISSUE TITLE
The "/var/www/html/lyfe/app/App/Http/Livewire/" directory does not exist.

### ISSUE THREAD

**Issue by Akanshgwl** [andrey-helldar/laravel-app#5]
After installing the package i am facing an error. please click on the below link (Laravel 8, Jetsteam, Livewire 2).
https://flareapp.io/share/Lm86nMR7

**Comment by andrey-helldar** [comment]
The functionality of the package changes the namespace of the application, but does not touch the information collected by the composer.

Run the command: `composer dumpauto`
